name: RpRoll
main: kingsAndGlory.RpRoll
version: 0.3
commands:
   roll:
      description: Rolls a number
      usage: /roll [number]
      #permission: RpRoll.roll
      #permission-message: You don't have RpRoll.roll